# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-case-conflict
    -   id: check-toml
-   repo: https://github.com/amperser/proselint
    # Use the latest version tag, check the GitHub repository for the most recent one
    rev: v0.16.0
    hooks:
    - id: proselint
      # Optional: restrict to specific file types (markdown, plain-text, etc.)
      types_or: [html, markdown, plain-text, tex]
-   repo: https://github.com/oxipng/oxipng
    rev: v10.1.0
    hooks:
      - id: oxipng
        args: ["-o", "4", "--strip", "safe", "--alpha"]
